site_name: Protoni's site
site_url: https://protoni.github.io/projects/

repo_url: https://github.com/protoni/projects
repo_name: protoni/projects
edit_uri: edit/main/docs/

# Set material theme settings
theme:
  name: material
  custom_dir: docs/stylesheets
#  icon:
#    edit: material/pencil 
#    view: material/eye

#  logo: assets/images/ohYouDogRound.PNG
#  favicon: assets/images/ohYouDogRound.PNG
  features:
#    - navigation.tabs
    - navigation.indexes
#    - navigation.instant
#    - navigation.sections
#    - toc.integrate
#    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    - scheme: slate
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
#      toggle:
#        icon: material/brightness-4
#        name: Switch to light mode    
      primary: indigo
      accent: lime

# Set plugins
plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: false
      type: timeago

# Use custom css
extra_css:
  - stylesheets/styles.css
  - stylesheets/commits.css
  - stylesheets/converter.css
  - stylesheets/threejs.css
  - stylesheets/terrain.css
  - stylesheets/audio_visualizer_sphere.css
  - stylesheets/diff.css

# Add custom javascript components
extra_javascript:
  - js/terrain.js
  - js/commits.js
  - js/converter.js
  - js/spectrogram.js
  - js/audio_visualizer_sphere.js
  - js/diff.js
  - https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js
  - https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js
  - https://cdnjs.cloudflare.com/ajax/libs/cannon.js/0.6.2/cannon.min.js
  

# Set md extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Remove default copyright text
extra:
  generator: false

# Set copyright text + contant info ( address encoded with email encoder)
copyright: Copyright &copy; 2023-> Protoni. Contant at &#116;&#111;&#110;&#105;&#032;[&#064;]&#032;&#112;&#114;&#111;&#116;&#111;&#110;&#105;&#046;&#102;&#105;