site_name: Protoni's site
site_url: https://protoni.github.io/projects/

# Set material theme settings
theme:
  name: material
#  logo: assets/images/ohYouDogRound.PNG
#  favicon: assets/images/ohYouDogRound.PNG
  features:
#    - navigation.tabs
    - navigation.indexes
#    - navigation.instant
#    - navigation.sections
#    - toc.integrate
#    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

# Set plugins
plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Use custom css
extra_css:
  - stylesheets/styles.css

# Set md extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Remove default copyright text
extra:
  generator: false

# Set copyright text + contant info ( address encoded with email encoder)
copyright: Copyright &copy; 2023-> Protoni. Contant at &#116;&#111;&#110;&#105;&#032;[&#064;]&#032;&#112;&#114;&#111;&#116;&#111;&#110;&#105;&#046;&#102;&#105;